# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f00e9051b72d39a1071847ba3858b53dc8d6b2315379d12d9cb667250339b3a369d6a5fb42fe3b25767b430b4ac2b17db0a51e8a9811c507f65845c2e709d28

test:
  secret_key_base: 497d4257731b034c902fcd428f46fd7e247cd9df1e3b23ca183dcc351fd36b7827fe3014cdfc742a3859d9a3bb3ed356924ff95aecd5bd811595539192e2c635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
